CREATE TEMPORARY TABLE RAW_PLAYER(PLAYERID BIGINT, COUNTRY CHAR(2), PLAYERSTATE VARCHAR(11));
LOAD DATA INFILE '/home/dingding/Documents/jobsearch_tasks/dimplayer_20170320.csv' INTO TABLE RAW_PLAYER FIELDS TERMINATED BY ';' LINES TERMINATED BY '\r' IGNORE 1 LINES (PLAYERID, COUNTRY, PLAYERSTATE, @dummy, @dummy, @dummy, @dummy);
CREATE TEMPORARY TABLE DIM_PLAYER_BK AS SELECT * FROM DIM_PLAYER;
UPDATE DIM_PLAYER d INNER JOIN RAW_PLAYER r ON d.PLAYERID = r.PLAYERID AND d.COUNTRY != r.COUNTRY SET d.VALIDTO = CURDATE()-1 WHERE d.VALIDTO IS NULL;
INSERT INTO DIM_PLAYER (PLAYERID, COUNTRY, PLAYERSTATE, VALIDFROM) SELECT r.*, CURDATE()  FROM RAW_PLAYER r INNER JOIN DIM_PLAYER_BK b ON r.PLAYERID = b.PLAYERID AND r.COUNTRY != b.COUNTRY WHERE b.VALIDTO IS NULL;
INSERT INTO DIM_PLAYER (PLAYERID, COUNTRY, PLAYERSTATE, VALIDFROM) SELECT *, CURDATE()  FROM RAW_PLAYER WHERE PLAYERID NOT IN (SELECT PLAYERID FROM DIM_PLAYER_BK);

 
